name: MooneliaReport
version: '1.0-SNAPSHOT'
author: DeathFull
main: fr.deathfull.mooneliaReport.MooneliaReport
api-version: '1.21'

commands:
  report:
    description: Envoyer un report sur Discord
    usage: /report <message>
    permission: moonelia.report
    permission-message: "§cVous n'avez pas la permission d'utiliser cette commande !"

permissions:
  moonelia.report:
    description: Permet d'utiliser la commande /report
    default: true

